apiVersion: v1
kind: Pod
metadata:
  # TODO: Replace SAMPLE-SERVICE by the name of your service
  # Use dash "-" and not underscore "_" in this file for the service name
  name: SAMPLE-SERVICE-pod
  labels:
    # TODO: Replace SAMPLE-SERVICE by the name of your service
    app: SAMPLE-SERVICE
spec:
  containers:
  # TODO: Replace SAMPLE-SERVICE by the name of your service
  - name: SAMPLE-SERVICE
    # TODO: Replace SAMPLE-SERVICE by the name of your service
    image: csia-pme/SAMPLE-SERVICE
    # As we use the local image, there is no need to pull the image
    imagePullPolicy: Never
    ports:
    - containerPort: 80 
    env:
    - name: APP_HOST
      value: 0.0.0.0
    - name: APP_PORT
      value: "80"
    - name: APP_LOG
      value: info
    - name: APP_ENGINE
      value: "http://engine-service:8080"
    - name: APP_SERVICE
      # TODO: Replace SAMPLE-SERVICE by the name of your service
      # TODO: Replace SAMPLE-SERVICE-PORT by the port used by your service
      value: "http://SAMPLE-SERVICE-service:SAMPLE-SERVICE-PORT"
    - name: APP_NOTIFY_CRON
      value: "30"
